import os
import shutil
from rich import print as rp


def make_icon_library() -> str:
    header = ("// ============================================ //\n"
              "// This file is generated by mk_icon_library.py //\n"
              "// Do not edit this file manually.              //\n"
              "// ============================================ //\n\n")
    content = header

    targets = os.listdir("src/uiEditor/icons")
    file_2_js = {}

    # Get all icons
    for icon_file in targets:
        js_name_ = icon_file.replace(".svg", "").split("-")
        js_name = js_name_[0] + ("".join(x[0].upper()+x[1:] for x in js_name_[1:]))
        import_stmt = f"import {js_name} from './icons/{icon_file}'\n"
        file_2_js[icon_file] = js_name
        content += import_stmt
    
    content += "\nexport default {\n"
    # Export all icons
    for icon_file in targets:
        js_name = file_2_js[icon_file]
        export_name = icon_file.replace(".svg", "")
        export_stmt = f"    [\"{export_name}\"]: {js_name},\n"
        content += export_stmt
    content += "}\n"
    
    return content


if __name__ == "__main__":
    rp("[bold green]Generating icon library...")
    content = make_icon_library()
    with open("src/uiEditor/iconLibrary.ts", "w") as f:
        f.write(content)
    rp("[bold green]Done!")
