// ============================================ //
// This file is generated by mk_icon_library.py //
// Do not edit this file manually.              //
// ============================================ //

import flexDirection_columnReverse from './icons/flex-direction_column-reverse.svg'
import flexDirection_column from './icons/flex-direction_column.svg'
import flexDirection_rowReverse from './icons/flex-direction_row-reverse.svg'
import flexDirection_row from './icons/flex-direction_row.svg'
import h_flexWrap_nowrap from './icons/h_flex-wrap_nowrap.svg'
import h_flexWrap_wrapReverse from './icons/h_flex-wrap_wrap-reverse.svg'
import h_flexWrap_wrap from './icons/h_flex-wrap_wrap.svg'
import h_justify_center from './icons/h_justify_center.svg'
import h_justify_flexEnd from './icons/h_justify_flex-end.svg'
import h_justify_flexStart from './icons/h_justify_flex-start.svg'
import h_justify_spaceAround from './icons/h_justify_space-around.svg'
import h_justify_spaceBetween from './icons/h_justify_space-between.svg'
import h_layout_fill from './icons/h_layout_fill.svg'
import h_layout_fixed from './icons/h_layout_fixed.svg'
import h_layout_push from './icons/h_layout_push.svg'
import h_layout_shrink from './icons/h_layout_shrink.svg'
import h_overflow_auto from './icons/h_overflow_auto.svg'
import h_overflow_clip from './icons/h_overflow_clip.svg'
import h_overflow_visible from './icons/h_overflow_visible.svg'
import v_flexWrap_nowrap from './icons/v_flex-wrap_nowrap.svg'
import v_flexWrap_wrapReverse from './icons/v_flex-wrap_wrap-reverse.svg'
import v_flexWrap_wrap from './icons/v_flex-wrap_wrap.svg'
import v_justify_center from './icons/v_justify_center.svg'
import v_justify_flexEnd from './icons/v_justify_flex-end.svg'
import v_justify_flexStart from './icons/v_justify_flex-start.svg'
import v_justify_spaceAround from './icons/v_justify_space-around.svg'
import v_justify_spaceBetween from './icons/v_justify_space-between.svg'
import v_layout_fill from './icons/v_layout_fill.svg'
import v_layout_fixed from './icons/v_layout_fixed.svg'
import v_layout_push from './icons/v_layout_push.svg'
import v_layout_shrink from './icons/v_layout_shrink.svg'
import v_overflow_auto from './icons/v_overflow_auto.svg'
import v_overflow_clip from './icons/v_overflow_clip.svg'
import v_overflow_visible from './icons/v_overflow_visible.svg'

export default {
    ["flex-direction_column-reverse"]: flexDirection_columnReverse,
    ["flex-direction_column"]: flexDirection_column,
    ["flex-direction_row-reverse"]: flexDirection_rowReverse,
    ["flex-direction_row"]: flexDirection_row,
    ["h_flex-wrap_nowrap"]: h_flexWrap_nowrap,
    ["h_flex-wrap_wrap-reverse"]: h_flexWrap_wrapReverse,
    ["h_flex-wrap_wrap"]: h_flexWrap_wrap,
    ["h_justify_center"]: h_justify_center,
    ["h_justify_flex-end"]: h_justify_flexEnd,
    ["h_justify_flex-start"]: h_justify_flexStart,
    ["h_justify_space-around"]: h_justify_spaceAround,
    ["h_justify_space-between"]: h_justify_spaceBetween,
    ["h_layout_fill"]: h_layout_fill,
    ["h_layout_fixed"]: h_layout_fixed,
    ["h_layout_push"]: h_layout_push,
    ["h_layout_shrink"]: h_layout_shrink,
    ["h_overflow_auto"]: h_overflow_auto,
    ["h_overflow_clip"]: h_overflow_clip,
    ["h_overflow_visible"]: h_overflow_visible,
    ["v_flex-wrap_nowrap"]: v_flexWrap_nowrap,
    ["v_flex-wrap_wrap-reverse"]: v_flexWrap_wrapReverse,
    ["v_flex-wrap_wrap"]: v_flexWrap_wrap,
    ["v_justify_center"]: v_justify_center,
    ["v_justify_flex-end"]: v_justify_flexEnd,
    ["v_justify_flex-start"]: v_justify_flexStart,
    ["v_justify_space-around"]: v_justify_spaceAround,
    ["v_justify_space-between"]: v_justify_spaceBetween,
    ["v_layout_fill"]: v_layout_fill,
    ["v_layout_fixed"]: v_layout_fixed,
    ["v_layout_push"]: v_layout_push,
    ["v_layout_shrink"]: v_layout_shrink,
    ["v_overflow_auto"]: v_overflow_auto,
    ["v_overflow_clip"]: v_overflow_clip,
    ["v_overflow_visible"]: v_overflow_visible,
}
